baseurl: ''
permalink: pretty
title: 'BIAS project'

logo:
  mobile: "images/logo/bias_logo.svg"
  mobile_height: "32px"
  mobile_width: "32px"
  desktop: "images/logo/bias_logo_rec.svg"
  desktop_height: "32px"
  desktop_width: "120px"

home: 
  limit_projects: 6

collections:
  projects:
    output: true
    sort_by: weight
  team:
    output: true

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "projects"
  - scope:
      path: ""
      type: "team"
    values:
      layout: "team"

sass:
  style: compressed # possible values: nested expanded compact compressed

plugins:
  - jekyll-environment-variables

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md
